> Dionysios Rigatos <br />
> dionysir@stud.ntnu.no <br />

[Back to assignment 7](_Oving7.ipynb)
# Gaussian Elimination

***if the math in the text is not showing up correctly, try double-clicking in the text-box and run the cell (shift+enter).***

#### Gaussian Elimination with partial pivoting

Gaussian elimination, or row reduction, is an algorithm for solving linear systems presented in augmented matrix form. It works by reducing an augmented matrix to a triangular form, before performing back substitution to obtain solution variables.

A linear system, here with three unknowns $x_0,x_1,x_2$ is of the form 
$$ a_{00}x_0 + a_{01}x_1 + a_{02}x_2 = b_0 $$
$$a_{10}x_0 + a_{11}x_1 + a_{12}x_2 = b_1$$
$$a_{20}x_0 + a_{21}x_1 + a_{22}x_2 = b_2.$$

We can represent it in the more abstract matrix form $Ax=b$, where
$$ A = 
\begin{bmatrix}
a_{00} & a_{01} & a_{02}\\
a_{10} & a_{11} & a_{12}\\
a_{20} & a_{21} & a_{22}
\end{bmatrix}, \quad
x = 
\begin{bmatrix}
x_{0}\\
x_{1}\\
x_{2}
\end{bmatrix}, \quad
b = 
\begin{bmatrix}
b_{0}\\
b_{1}\\
b_{2}
\end{bmatrix}.$$


To solve a linear system by Gaussian elimination, we first state it in *augmented* form


$$\left[\begin{array}{ccc|c}
a_{00} & a_{01} & a_{02} & b_{0} \\
a_{10} & a_{11} & a_{12} & b_{1} \\
a_{20} & a_{21} & a_{22} & b_{2}
\end{array}\right]$$

Then, we reduce it to a triangular form using row operations only, in a systematic fashion. We start with the *pivot column* being column no. 0 and the pivot row being row no. 0. Then we repeat the following pattern:

1. Find the maximum entry (in absolute value) in the pivot column from the pivot row to the bottom.
    - If this is not possible (i.e. all rows below the pivot row, including the pivot row have 0 in the pivot column), increase the index of the pivot column by 1 and repeat.
2. Swap the entries in the pivot row and the row with the maximum value.
3. Add multiples of the pivot row to the rows below such that the pivot column has only 0 entries after the pivot row. This means: If the pivot element has value $a_{ij}$ and the element of same column in a later row has value $a_{kj}$, add $\frac{-a_{kj}}{a_{ij}}$ multiples of the pivot row to that row.
4. Increase the numbering of the pivot row and the pivot column by 1.
5. If the pivot row is the last row and/or if the pivot column number exceeds the number of columns in the matrix (not counting the extra column with $b_0,b_1,b_2$ ), stop the iterations. Otherwise, repeat from step 1.

This procedure changes the entries in the matrix, which we in general now call $\tilde{a}_{ij}$. The matrix should now be in *upper triangular* or *echelon form*:
$$\left[\begin{array}{ccc|c}
\tilde{a}_{00} & \tilde{a}_{01} & \tilde{a}_{02} & \tilde{b}_{0} \\
0 & \tilde{a}_{11} & \tilde{a}_{12} & \tilde{b}_{1} \\
0 & 0 & \tilde{a}_{22} & \tilde{b}_{2}
\end{array}\right].$$

This corresponds to the linear system

$$\tilde{a}_{00}x_0 + \tilde{a}_{01}x_1 + \tilde{a}_{02}x_2 = \tilde{b}_0$$
$$\tilde{a}_{11}x_1 + \tilde{a}_{12}x_2 = \tilde{b}_1$$
$$ \tilde{a}_{22}x_2 = \tilde{b}_2.$$


We can easily solve this system by backsubstitution, observing that $\tilde{x}_{2} = \frac{\tilde{b}_2}{\tilde{a}_{22}},$, and that $\tilde{x}_{1} = \frac{\tilde{b}_1 - \tilde{a}_{12}x_2}{\tilde{a}_{11}}.$ In general, after reducing the matrix to upper triangular form we can deduce that for a system of $n$ unknowns, $$ x_j = \frac{\tilde{b}_j - \sum_{k = j+1}^{n}\tilde{a}_{jk}x_k }{\tilde{a}_{jj}}.$$


**Example** 

Consider a linear system with the following augmented matrix
$$ \left[\begin{array}{ccc|c}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 1 & 2
\end{array}\right].$$
From step 2, we swap the first row with the thrid row such that the pivot element is the largest in the pivot column
$$\left[\begin{array}{ccc|c}
8 & 9 & 1 & 2\\
4 & 5 & 6 & 7 \\
0 & 1 & 2 & 3 
\end{array}\right].$$

Following step no. 3, we add (-4/8 = -0.5) times the pivot row to row no.1 and (0/4 = 0) times the pivot row to row no. 2 and get
$$ \left[\begin{array}{ccc|c}
8 & 9 & 1 & 2 \\
0 & 0.5 & 5.5 & 6 \\
0 & 1 & 2 & 3 
\end{array}\right].$$

Then, from step 4 we increase the numbering of pivot row and column, so our pivot row is 1 and pivot column is also 1. Checking step 5, we do not yet terminate. Returning to step 1, we find the maximal element in column no 1 from row 1 and onward in row 2. Therefore, as in step 2, we swap rows 1 and 2 to get 

$$ \left[\begin{array}{ccc|c}
8 & 9 & 1 & 2 \\
0 & 1 & 2 & 3 \\
0 & 0.5 & 5.5 & 6 
\end{array}\right].$$

We then follow step 3, adding a multiple of (-0.5/1 = -0.5) of row 1 to row 2, yielding
$$
\left[\begin{array}{ccc|c}
8 & 9 & 1 & 2 \\
0 & 1 & 2 & 3 \\
0 & 0 & 4.5 & 4.5 
\end{array}\right].$$

After step 4, we have row and column indices of 2, which means we are on the final row and so we stop the iterations after step 5.

The above system can be solved by back substitution to find $ x_3 = 1, x_2 = 1, x_1 = -1.$


## a)

Assign the variable `matrix` for the augmented matrix of the set of equations

$$
x - 2y + 1z = 0$$
$$\quad\quad 2y - 8z = 8$$
$$ -4x + 5y + 9z = -9$$

***Write code in the block below***

In [1]:
import numpy as np

matrix = np.array([[1, -2, 1, 0],
                   [0, 2, -8, 8],
                   [-4, 5, 9, -9]])

## b) 
Make a function `add` that takes a matrix `A` and adds a multiple of one row to another. The function should accept `A`, two integers `i1` and `i2` as input (the integers specify which rows to add) and a number `num`. The function should take the rows `A[i1,:]` and `A[i2,:]` then add `num*A[i1,:]` to `A[i2,:]`. The function shall not return anything, but only make changes to `A[i2,:]`.

**Example run**

```python
A = np.array([[2.,3.,4.], [5.,-3.,6.]])
add(A,0, 1, -5/2) # add (-5/2) times row 0 to row 1
print(A)
  
#Running the code produces the following output:
[[  2.    3.    4. ]
 [  0.  -10.5  -4. ]]
```
***Write code in the block below***

In [2]:
def add(A, i1, i2, num):
    pivot_row = A[i1, :]
    A[i2, :] += num * pivot_row

In [3]:
A = np.array([[2.,3.,4.], [5.,-3.,6.]])
add(A,0, 1, -5/2) 
print(A)

[[  2.    3.    4. ]
 [  0.  -10.5  -4. ]]


## c)

Make a function `swap` that takes a matrix `A` and two integers `i1` and `i2`, and then swaps the `i1` and `i2` rows of `A`. The function shall not return anything, just swaps the rows in `A`.

**Example run**
```python
A = np.array([[2.,3.,4.], [5.,-3.,6.]])
swap(A,0, 1)
print(A)
  
#Running the code produces the following output:
[[ 5. -3.  6.]
 [ 2.  3.  4.]]
```
***Hint:***
you may need to define a temporary variable to save the information in a row before swapping the rows around. E.g.,  `temp = np.array(A[i1,:])`. Also note that you have to have the `np.array` here even tho `A` is already an np.array.

***Write code in the block below***


In [4]:
def swap(A, i1, i2):
    target_row = A[i1, :].copy()
    A[i1, :] = A[i2, :].copy()
    A[i2, :] = target_row

In [5]:
A = np.array([[2.,3.,4.], [5.,-3.,6.]])
swap(A, 0, 1)
print(A)

[[ 5. -3.  6.]
 [ 2.  3.  4.]]


## d)
Write a function `getMaxRow` that takes an augmented matrix `A` (with `n` rows and `n+1` columns) and two integers `i` and `j` that specify the row and column of the pivot element. The function should return the index of the row with the largest element below the pivot row. The function should search down through the $j$'th column starting from the $i$'th row and return the *row index* of the element with maximal absolute value. This corresponds to step 1 above.

**Example run**
```python

A = np.array([[0.,1.,2.,3.], [4.,5.,6.,7.], [8.,9.,1.,2.]])
print(getMaxRow(A,0,0)) 
  
#In the 0th column, the row with the largest element is in row 2 so the above code should return:
#2
```

***Hint:***

If `A` is an n x (n+1) matrix, you can use the built-in function `n = len(A)` to find n. (this returns the row dimension of `A`, regardless of the column dimension)

The array `A[i:n,j]` returns the elements in the column below and including the pivot element.

***write code in block below***


In [6]:
def getMaxRow(A, i, j):
    return np.argmax(np.abs(A[i:, j]))

In [7]:
A = np.array([[0.,1.,2.,3.], [4.,5.,6.,7.], [8.,9.,1.,2.]])
print(getMaxRow(A,0,0)) 

2


## e)

Write a function `rowOps` that takes as arguments a matrix `A` and two index numbers `i` and `j` that specify the pivot element. The function should first check whether `A[i,j]==0`, and return without doing anything if true. Otherwise, the function should add appropriate multiples of `A[i,:]` to each row with index larger than `i` in `A`, such that its entry with index `j` (i.e., in the pivot row) is set to zero.  This corresponds to step 3 above.

**example run**
```python
#Example 1:
A = np.array([[0.,1.,1.,3.], [1.,2,3,0], [1.,3.,4.,-2.]])
rowOps(A,0,0)
print(A)
  
#Running the code produces the following output:
[[ 0.  1.  1.  3.]
 [ 1.  2.  3.  0.]
 [ 1.  3.  4. -2.]]
#Nothing is changed since A[0,0]=0.
  
  
#Example 2
A = np.array([[8.,1.,1.,3.], [2.,6.,3.,0.], [4.,3.,4.,-2.]])
rowOps(A,0,0)
print(A)
  
#Running the code in example 2 produces the following output:
[[ 8.    1.    1.    3.  ]
 [ 0.    5.75  2.75 -0.75]
 [ 0.    2.5   3.5  -3.5 ]]
```
***Hint:*** 

Remember to use floats in your matrix `A` and not integers otherwise you might get the wrong result as arithmatic with integers are rounded, which is not what we want. This is done by putting a decimal point after each number (that is, we write `2.` instead of `2`).

***Write code in block below*** 

In [8]:
def rowOps(A, i, j):
    if A[i, j] == 0.:
        return True
    
    for k in range(i + 1, A.shape[0]):
        mult = -A[k, j]/A[i, j]
        add(A, i, k, mult)

In [9]:
A = np.array([[0.,1.,1.,3.], [1.,2,3,0], [1.,3.,4.,-2.]])
rowOps(A,0,0)
print(A)

[[ 0.  1.  1.  3.]
 [ 1.  2.  3.  0.]
 [ 1.  3.  4. -2.]]


In [10]:
A = np.array([[8.,1.,1.,3.], [2.,6.,3.,0.], [4.,3.,4.,-2.]])
rowOps(A,0,0)
print(A)

[[ 8.    1.    1.    3.  ]
 [ 0.    5.75  2.75 -0.75]
 [ 0.    2.5   3.5  -3.5 ]]


#### Hint

Use the add function implemented in b) to add rows

Use a for loop that takes you over all the rows below the pivot row

If the pivot column has index `j` and the pivot row has index `i`, you should add (`-A[k,j]/A[i,j]`) times the pivot row to zero out row number `k`.

## f)
Now make a function `Gauss` that takes a matrix `A` as and uses `getMaxRow`, `rowOps` and `swap` functions to perform a Gaussian elimination with partial pivoting on `A`.

**Example run:**
```python
A = np.array([[0.,1.,2.,3.], [4.,5.,6.,7.], [8.,9.,1.,2.]])
 
Gauss(A)
print(A)
  
#Running the code produces the following output
[[8.  9.  1.  2. ]
 [0.  1.  2.  3. ]
 [0.  0.  4.5 4.5]]
```

***Hint***

There are many ways to approach this problem. One possible way is with a for loop: `for i in range(0,n):` where `n` is the row dimension of `A`

You should use your functions `getMaxRows`, `swap` and `rowOps` within the loop. 

Make use of the pseudocode (steps 1-5) above.

Every time you use row_ops, increase both the row and column indices of your pivot element.

***write code in block below***

In [11]:
def Gauss(A) -> None:
    for i in range(A.shape[0]):
        row = getMaxRow(A, i, i)
        swap(A, i, row + i)
        if rowOps(A, i, i):
            return
            

In [12]:
A = np.array([[0.,1.,2.,3.], [4.,5.,6.,7.], [8.,9.,1.,2.]])
 
Gauss(A)
print(A)

[[8.  9.  1.  2. ]
 [0.  1.  2.  3. ]
 [0.  0.  4.5 4.5]]


## Bonus question! (optional) 

Make a function  `backSubs` that takes as input a matrix `A` in *echelon form*, and performs *back substitution*, returning a list containing the solution to the system.

Call the functions `Gauss` and `backSubs` on the matrix from a), and print the results.

**example run**
```python
#Example 1
A = np.array([[1.,1.,1.,3.], [1.,2.,3.,0.], [1.,3.,4.,-2.]])
Gauss(A)
x = backSubs(A)
print(x)
  
#Running this code produces this output:
[ 5. -1. -1.]
```
**Hint:**
Remember a sum should be implemented using a `for` loop. For example $$c = \sum_{k=0}^{10} 2^{-n}$$ is implemented in Python via 
```python
c = 0
for k in range(0,10):
    c = c + 2**(-k)
    
```